# Generated by Django 4.0.3 on 2022-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=50)),
                ('attraction_description', models.CharField(max_length=300)),
                ('attraction_open_time', models.CharField(max_length=100)),
                ('attraction_address', models.CharField(max_length=50)),
                ('attraction_region', models.CharField(max_length=10)),
                ('attraction_town', models.CharField(max_length=10)),
                ('attraction_tel', models.CharField(max_length=20)),
                ('attraction_pic', models.CharField(max_length=100)),
                ('attraction_px', models.FloatField()),
                ('attraction_py', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_description', models.CharField(max_length=300)),
                ('food_open_time', models.CharField(max_length=100)),
                ('food_address', models.CharField(max_length=50)),
                ('food_region', models.CharField(max_length=10)),
                ('food_town', models.CharField(max_length=10)),
                ('food_tel', models.CharField(max_length=20)),
                ('food_pic', models.CharField(max_length=100)),
                ('food_px', models.FloatField()),
                ('food_py', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_description', models.CharField(max_length=300)),
                ('hotel_address', models.CharField(max_length=50)),
                ('hotel_region', models.CharField(max_length=10)),
                ('hotel_town', models.CharField(max_length=10)),
                ('hotel_tel', models.CharField(max_length=20)),
                ('hotel_pic', models.CharField(max_length=100)),
                ('hotel_px', models.FloatField()),
                ('hotel_py', models.FloatField()),
            ],
        ),
    ]
