# Generated by Django 4.0.3 on 2022-03-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attraction_description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description',
            field=models.CharField(max_length=800),
        ),
    ]
