# Generated by Django 4.0.3 on 2022-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_attraction_attraction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attraction_tel',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_tel',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_tel',
            field=models.CharField(max_length=40),
        ),
    ]
