# Generated by Django 4.0.3 on 2022-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_attraction_attraction_tel_alter_food_food_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attraction_description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_description',
            field=models.CharField(max_length=3000),
        ),
    ]
