# Generated by Django 4.0.3 on 2022-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_alter_attraction_attraction_open_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='attraction_pic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_pic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_pic',
            field=models.CharField(max_length=200),
        ),
    ]
